library(magrittr)
library(org.Hs.eg.db)
library(clusterProfiler)
library(enrichplot)
library(AnnotationDbi)
library(stringr)
library(cowplot)
library(pathview)
library(ggplot2)
library(tibble)
library(readr)
library(dplyr)
library(tidyr)
library(ggbeeswarm)
library(paletteer)

counts = read_csv("/users/mkelsey/data/senescence/results/agg/deseq2/star/condition_SEN_vs_PRO/counttablesizenormed.csv")
head(counts)
mat = counts %>% filter(...1 == "PPP1R12C") %>% t()
df = data.frame(mat)
df
df$samples = rownames(df)
df = df %>% tibble()
p = df %>%
  filter(!row_number() %in% c(1)) %>% mutate_at("mat", as.numeric) %>%
    ggplot() + ylab("counts") + ylim(0, 6000) +
    geom_point(aes(x = samples, y = mat)) + coord_flip()
pdf("PPP1R12C.pdf", width = 3, height = 3)
print(p)
dev.off()
head(counts)
tail(counts,n =100)
print(tail(counts, n=100),n=100)
quantile(counts$PRO1[counts$PRO1 > 0], probs = seq(0,1,0.1)) %>% as.integer()
